import Head from "next/head";
import React from "react";
import { META } from "../../constants/config";
// import styles from "./layout.module.css";
import { Navbar } from "../Navbar";
import { LeftMenu } from "../LeftMenu";
import { Footer } from "../Footer";
import EmptyCard from "../Loading/EmptyCard";

interface Props {
  title: string;
  children: React.ReactNode;
}

export default function Layout({
  title,
  children,
}: Props) {  

  const styles = {};

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta content={META.theme} name="theme-color" />
        <meta content={META.description} name="description" />
        <meta content={META.keywords} name="keywords" />
        <meta content={META.author} name="author" />
        <meta content={META.author} property="og:site_name" />
        <meta content={META.fbapp} property="fb:app_id" />
        <meta content="summary_large_image" name="twitter:card" />
        <meta content={META.twitter} name="twitter:creator" />
        <meta content={META.twitter} name="twitter:site" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={styles.main}> */}
      <main>
        <Navbar />
        {/* {
          withMenu && <LeftMenu asideCss={asideCss} />
        } */}       

        {children}       

        {/* <section className={styles.section}>{children}</section> */}
        {/* <section style={styles.section}>{children}</section> */}
        <Footer />
      </main>
    </>
  );
}
